function [minl,maxl,flag]=Check(str)
%{
    需要完成的功能：表达式的检查，异或的展开，括号展开（分配律）
    我们先完成异或，括号两项的检查与展开，分为两部分：
    首先完成括号展开
    1.完成对括号匹配的检查和括号位置的记录
    2.利用递归函数，完成括号展开
    如果出现xor则直接展开成异或
    首先只允许出现'+','\'','(',')',英文字母这四种情况。
%}
str=upper(str);
str=char(str);
letvec=isletter(str);
letter=str(letvec==1);
numerics=abs(letter);
temp=minmax(numerics);
minl=temp(1);
maxl=temp(2);
flag=1;
end